[package]
name = "csv-search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
nom = "7.1.3"
thiserror = "1.0.65"
